[package]
name = "my-dapp"
version = "1.0.0"
authors = []

[addresses]
move-tut_addr = "0x6edbe203716b31cdd270e632649476c4495fba6f86238632a525fbd7a9702ded"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
